// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7Sy-JmJuWvFfRarS11p0G8fF4WoCl2Q',
    appId: '1:969787167975:web:e04a1c32487760e72b7e42',
    messagingSenderId: '969787167975',
    projectId: 'anuchats-d1540',
    authDomain: 'anuchats-d1540.firebaseapp.com',
    storageBucket: 'anuchats-d1540.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_180loaiMWI__PFP2QRmIdcQmEhgdC4A',
    appId: '1:969787167975:android:ac6b34cddea166ef2b7e42',
    messagingSenderId: '969787167975',
    projectId: 'anuchats-d1540',
    storageBucket: 'anuchats-d1540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbEyLnA-B-gbvKYAbXSlsQ3pWJPvoxtHo',
    appId: '1:969787167975:ios:4091edbd92677e272b7e42',
    messagingSenderId: '969787167975',
    projectId: 'anuchats-d1540',
    storageBucket: 'anuchats-d1540.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbEyLnA-B-gbvKYAbXSlsQ3pWJPvoxtHo',
    appId: '1:969787167975:ios:4091edbd92677e272b7e42',
    messagingSenderId: '969787167975',
    projectId: 'anuchats-d1540',
    storageBucket: 'anuchats-d1540.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP7Sy-JmJuWvFfRarS11p0G8fF4WoCl2Q',
    appId: '1:969787167975:web:f870a9efaaeef3d72b7e42',
    messagingSenderId: '969787167975',
    projectId: 'anuchats-d1540',
    authDomain: 'anuchats-d1540.firebaseapp.com',
    storageBucket: 'anuchats-d1540.appspot.com',
  );

}